Repository Attica-org/athens-client, pull requests merged in 2024-06, with the labels that each got.

#21 채팅 공유 모달 뒤 채팅 안보이는 버그, 아고라 직접 접근 시 404페이지 리다이렉트 버그 수정
  public/opengraph.png
  src/app/(chat)/agoras/[agora]/@modal/(.)flow/social-share/page.tsx
  src/app/not-found.tsx
  src/lib/fetchWrapper.ts
  src/lib/getReissuanceToken.ts
  src/middleware.ts
Labels: Type: Bug, Priority: High, fix

#22 모바일/태블릿 모드 css 변경, fetchWrapper retry 모든 에러에 적용
  public/img/kakao_logo.png
  src/app/(chat)/_components/atoms/HamburgerButton.tsx
  src/app/(chat)/_components/atoms/SocialShareLogos.tsx
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/molecules/ShareButton.tsx
  src/app/(chat)/_components/templates/ResultAgora.tsx
  src/app/(chat)/layout.tsx
  src/app/(main)/_components/atoms/AgoraPointColor.tsx
  src/app/(main)/_components/atoms/ControlNumberInput.tsx
  src/app/(main)/_components/atoms/PageTitle.tsx
  src/app/(main)/_components/atoms/SearchBar.tsx
  src/app/(main)/_components/molecules/DiscussionDurationSetter.tsx
  src/app/(main)/create-agora/page.tsx
  src/app/(main)/flow/enter-agora/_components/InputErrorMessage.tsx
  src/app/_components/atoms/RedirectCheck.tsx
  src/app/_components/molecules/ModalBase.tsx
  src/app/globals.css
  src/assets/icons/CopyContentIcon.tsx
  src/lib/fetchWrapper.ts
Labels: Type: Maintenance, Priority: Medium, refactor

#25 ErrorBoundary 처리, CRLF / LF 충돌 문제 해결 , 무한 retry 문제 일부 완화
  .eslintrc.json
  package.json
  src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
  src/app/(chat)/_components/organisms/ErrorBoundaryMessage.tsx
  src/app/(chat)/agoras/[agora]/page.tsx
  src/app/(main)/_components/organisms/SearchDeciderSuspense.tsx
  src/app/_components/templates/ErrorFallback.tsx
  src/lib/fetchWrapper.ts
  yarn.lock
Labels: Priority: High, feat, chore, fix

#27 Fix : ErrorBoundary 래핑시 렌더링 중 컴포넌트 정의 문제 해결
  .eslintrc.json
  src/app/(main)/_components/molecules/SearchDecider.tsx
  src/app/(main)/_components/organisms/SearchDeciderSuspense.tsx
Labels: Priority: High, fix

#28 아고라 강제종료 및 에러 코드 추가
  .github/ISSUE_TEMPLATE/gitmessage.txt
  .github/ISSUE_TEMPLATE/pull_request_template.md
  src/app/(chat)/_components/atoms/DiscussionTimer.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(chat)/_components/molecules/ShareButton.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_lib/patchAgoraEnd.ts
  src/app/(chat)/_lib/patchAgoraStart.ts
  src/app/(chat)/_lib/patchAgoraTimeOut.ts
  src/app/(main)/_components/molecules/SearchDecider.tsx
Labels: Type: Enhancement, Status: In Progress, Priority: High, feat

#29 docs: LICENSE 추가
  LICENSE
Labels: Type: Maintenance, Priority: Low

#30 [#23] Issue 처리
  src/app/(chat)/_lib/getAgoraUsers.ts
  src/app/(chat)/_lib/getChatMessages.ts
  src/app/(main)/_lib/getAgoraCategorySearch.ts
  src/app/(main)/_lib/getAgoraKeywordSearch.ts
  src/lib/fetchWrapper.ts
Labels: Priority: High, feat, fix

#33 Fix: retry 3회 초과시 이후 API 요청이 안되는 것 수정
  src/lib/fetchWrapper.ts
Labels: Priority: High, fix

#32 프리티어 커밋 전 자동 검사 추가
  .github/gitmessage.txt
  .github/pull_request_template.md
  .prettierrc
  package.json
  yarn.lock
Labels: Type: Maintenance, Priority: High, chore

#34 Fix: merge 충돌 해결을 위한 commit
  src/lib/getReissuanceToken.ts
Labels: Priority: High, fix

#38 종료된 아고라 소켓 미연결 및 필요없는 정보 미출력
  src/app/(chat)/_components/atoms/ChatNotification.tsx
  src/app/(chat)/_components/atoms/SocialShareLogos.tsx
  src/app/(chat)/_components/molecules/AgoraTitle.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(main)/flow/enter-agora/_components/EnterAgoraButton.tsx
Labels: Status: Done, Type: Maintenance, Priority: High, refactor

#42 [#40] Fix: 토큰 재발급, 발급 함수 api retry 문제 해결
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_lib/getAgoraUsers.ts
  src/app/(chat)/_lib/getChatMessages.ts
  src/app/(chat)/_lib/getVoteResult.ts
  src/app/(chat)/_lib/patchAgoraEnd.ts
  src/app/(chat)/_lib/patchAgoraStart.ts
  src/app/(chat)/_lib/patchAgoraTimeOut.ts
  src/app/(main)/_lib/getAgoraTitle.ts
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/lib/fetchWrapper.ts
  src/lib/getReissuanceToken.ts
  src/lib/getToken.ts
  src/lib/retryConfig.ts
Labels: Type: Bug, Priority: High, fix

#43 채팅방 메타데이터 버그 수정
  src/app/(chat)/_components/molecules/DiscussionStatus.tsx
  src/app/(chat)/_components/organisms/AgoraUserSide.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/layout.tsx
  src/store/chatInfo.ts
Labels: Type: Bug, Type: Enhancement, Priority: High, fix

#44 채팅 레이아웃 변경 이슈
  src/app/(chat)/_components/organisms/AgoraUserSide.tsx
  src/app/(chat)/layout.tsx
Labels: Priority: Urgent

#45 design: 키보드로 화면 밀림 현상 테스트
  src/app/(chat)/layout.tsx
Labels: Priority: Urgent

#46 Fix : 채팅 헤더 밀림 현상 수정
  src/app/(chat)/agoras/[agora]/page.tsx
  src/app/(chat)/layout.tsx
Labels: Type: Bug, Priority: High, fix

#47 Fix : 채팅 헤더 밀림 현상 수정
  src/app/(chat)/layout.tsx
Labels: Type: Bug, Priority: High, fix

#48 Fix : 채팅 헤더 밀림 현상 수정
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/layout.tsx
Labels: Type: Bug, Priority: High, fix

#49 design: 채팅 자판에 의한 화면 밀림 수정 테스트
  src/app/(chat)/agoras/[agora]/page.tsx
  src/app/(chat)/layout.tsx
Labels: Priority: Urgent

#50 design: fixed sticky로 되돌림
  src/app/(chat)/agoras/[agora]/page.tsx
  src/app/(chat)/layout.tsx
Labels: Priority: Urgent

#56 [#52] 종료 아고라 입장시 바로 입장, 아고라 생성 후 전역 상태 reset
  src/app/(main)/_components/atoms/Agora.tsx
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
  src/store/create.ts
Labels: Status: Done, Type: Maintenance, Priority: High, fix

#57 채팅방 요구사항 및 버그 일부 수정
  src/app/(chat)/_components/atoms/SocialShareLogos.tsx
  src/app/(chat)/_components/molecules/ShareButton.tsx
  src/app/(chat)/_components/templates/SocialShare.tsx
  src/app/(main)/_components/atoms/NoAgoraMessage.tsx
  src/app/(main)/_components/templates/Main.tsx
Labels: Priority: Urgent

#58 투표 시간 비동기화 문제 및 탭 간 데이터 공유 문제 수정
  public/custom-sw.js
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/templates/EndAgora.tsx
  src/app/_components/utils/ServiceWorkerRegistration.tsx
  src/app/_components/utils/indexedDB.ts
  src/hooks/useVote.tsx
  src/utils/SWManager.ts
  tsconfig.json
Labels: Type: Bug, Priority: High, fix

#59 toast ui 커스텀
  src/app/(chat)/_components/molecules/DiscussionStatus.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/templates/EndAgora.tsx
  src/app/_components/molecules/ModalBase.tsx
Labels: Type: Maintenance, Priority: High, refactor

#61 Retry 오류 token 개별 관리, Modal 닫힐 때 reset 설정, [#53] 종료 투표 후, disabled 설정
  src/app/(chat)/_components/molecules/DiscussionStatus.tsx
  src/app/_components/molecules/ModalBase.tsx
  src/lib/fetchWrapper.ts
  src/lib/getReissuanceToken.ts
  src/lib/getToken.ts
  src/lib/retryConfig.ts
Labels: Status: Done, Type: Maintenance, Priority: High, refactor
