Repository Attica-org/athens-client, pull requests merged in 2024-11, with the labels that each got.

#109 몇 가지 문제 해결
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
Labels: Type: Maintenance, Priority: Urgent, fix

#113 클라이언트에서 서버 코드 호출로 인한 버그 수정
  public/custom-sw.js
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/templates/EndAgora.tsx
  src/app/(chat)/_lib/getAgoraUsers.ts
  src/app/(chat)/_lib/getChatMessages.ts
  src/app/(chat)/_lib/getVoteResult.ts
  src/app/(chat)/_lib/patchAgoraEnd.ts
  src/app/(chat)/_lib/patchAgoraImg.ts
  src/app/(chat)/_lib/patchAgoraStart.ts
  src/app/(chat)/_lib/patchAgoraTimeOut.ts
  src/app/(chat)/_lib/patchChatExit.ts
  src/app/(chat)/_lib/postFilterBadWords.ts
  src/app/(chat)/agoras/[agora]/page.tsx
  src/app/(main)/_components/organisms/EnterAgoraContent.tsx
  src/app/(main)/_lib/getAgoraTitle.ts
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/(main)/flow/enter-agora/_components/EnterAgoraButton.tsx
  src/app/config/RQProvider.tsx
  src/auth.config.ts
  src/hooks/useApiError.ts
  src/hooks/useUpdateSession.ts
  src/hooks/useVote.tsx
  src/lib/fetchWrapper.ts
  src/lib/getReissuanceToken.ts
  src/middleware.ts
  src/serverActions/auth.ts
  src/utils/isNull.ts
Labels: Priority: High, refactor, fix

#114 몇 가지 문제 해결, 유저 입퇴장 기능 구현
  public/mockServiceWorker.js
  src/app/(chat)/_components/atoms/UserAccessNotification.tsx
  src/app/(chat)/_components/atoms/UserExitNotification.tsx
  src/app/(chat)/_components/atoms/UserJoinNotificationt.tsx
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/templates/EndAgora.tsx
  src/app/(chat)/_lib/getChatMessages.ts
  src/app/(chat)/_lib/getVoteResult.ts
  src/app/(chat)/_lib/patchAgoraEnd.ts
  src/app/(chat)/_lib/patchAgoraImg.ts
  src/app/(chat)/_lib/patchAgoraStart.ts
  src/app/(chat)/_lib/patchChatExit.ts
  src/app/(chat)/_lib/postFilterBadWords.ts
  src/app/(main)/_components/atoms/KickedUserAlert.tsx
  src/app/(main)/_components/atoms/NavIconDecider.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/_components/molecules/NavLinks.tsx
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/(main)/user-info/_component/atoms/AccountInfo.tsx
  src/app/(main)/user-info/_component/atoms/ActionButton.tsx
  src/app/(main)/user-info/_component/molecules/AccountInfos.tsx
  src/app/(main)/user-info/_component/molecules/ActionButtons.tsx
  src/app/(main)/user-info/_component/molecules/Main.tsx
  src/app/(main)/user-info/_component/organisms/Main.tsx
  src/app/(main)/user-info/layout.tsx
  src/app/(main)/user-info/page.tsx
  src/app/globals.css
  src/app/model/Message.ts
  src/assets/icons/UserIcon.tsx
  src/constants/Auth.ts
  src/constants/segmentKey.ts
  src/middleware.ts
  src/utils/swalAlert.ts
  types/next-auth.d.ts
Labels: Type: Enhancement, Type: Maintenance, Priority: Urgent, feat, chore, refactor, fix

#115 토큰 재발급 후 기존 네트워크 요청 재요청
  src/app/(chat)/_components/atoms/DiscussionTimer.tsx
  src/app/(chat)/_components/atoms/ObserverStatus.tsx
  src/app/(chat)/_components/molecules/AgoraInfo.tsx
  src/app/(chat)/_components/molecules/DiscussionStatus.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(chat)/_components/molecules/ModifyAgoraImage.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/utils/SocketErrorHandler.ts
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
  src/app/(main)/flow/enter-agora/_components/EnterAgoraButton.tsx
  src/app/config/RQProvider.tsx
  src/app/not-found.tsx
  src/constants/AuthErrorMessage.ts
  src/constants/responseErrorMessage.ts
  src/hooks/useApiError.ts
  src/hooks/useUpdateSession.ts
  src/lib/fetchWrapper.ts
Labels: Priority: High, refactor, fix

#119 채팅방 투표 모달 불필요한 리렌더링 제어
  public/custom-sw.js
  src/app/(chat)/_components/atoms/ObserverStatus.tsx
  src/app/(chat)/_components/atoms/VoteActionButtons.tsx
  src/app/(chat)/_components/atoms/VoteResultLoader.tsx
  src/app/(chat)/_components/atoms/VoteTimer.tsx
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/templates/EndAgora.tsx
  src/app/(chat)/_lib/getAgoraUsers.ts
  src/app/(chat)/_lib/getChatMessages.ts
  src/app/(chat)/_lib/getVoteResult.ts
  src/app/(chat)/_lib/patchAgoraEnd.ts
  src/app/(chat)/_lib/patchAgoraImg.ts
  src/app/(chat)/_lib/patchAgoraStart.ts
  src/app/(chat)/_lib/patchAgoraTimeOut.ts
  src/app/(chat)/_lib/patchChatExit.ts
  src/app/(chat)/_lib/postFilterBadWords.ts
  src/app/(chat)/utils/ServiceWorkerErrorHandler.ts
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/(main)/user-info/_component/molecules/AccountInfos.tsx
  src/app/(main)/user-info/_component/molecules/ActionButtons.tsx
  src/auth.config.ts
  src/constants/responseErrorMessage.ts
  src/hooks/useApiError.ts
  src/hooks/useUpdateSession.ts
  src/lib/fetchWrapper.ts
  src/middleware.ts
  src/utils/postServiceWorkerMessage.ts
  src/utils/validation/validateIsNull.ts
  src/utils/validation/validateIsServiceWorkerActive.ts
  types/next-auth.d.ts
Labels: Type: Maintenance, Priority: Medium, refactor, fix

#120 소셜 로그인 메서드 POST에서 GET으로 변경
  src/app/robots.ts
  src/serverActions/auth.ts
Labels: Priority: Urgent, fix

#124 서비스워커 캐싱 적용 및 오프라인 API 응답 반환
  public/custom-sw.js
  src/app/(chat)/_lib/getAgoraUsers.ts
  src/app/(chat)/_lib/getChatMessages.ts
  src/app/(chat)/_lib/getVoteResult.ts
  src/app/(chat)/_lib/patchAgoraEnd.ts
  src/app/(chat)/_lib/patchAgoraImg.ts
  src/app/(chat)/_lib/patchAgoraStart.ts
  src/app/(chat)/_lib/patchAgoraTimeOut.ts
  src/app/(chat)/_lib/patchChatExit.ts
  src/app/(chat)/_lib/postFilterBadWords.ts
  src/app/(main)/_lib/getAgoraCategorySearch.ts
  src/app/(main)/_lib/getAgoraKeywordSearch.ts
  src/app/(main)/_lib/getAgoraTitle.ts
  src/app/(main)/_lib/getLivelyAgora.ts
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/(main)/page.tsx
  src/app/(main)/user-info/_component/molecules/ActionButtons.tsx
  src/app/(main)/user-info/_component/organisms/UserInfoMain.tsx
  src/app/(main)/user-info/page.tsx
  src/constants/responseErrorMessage.ts
  src/middleware.ts
Labels: Type: Maintenance, Priority: Medium, refactor

#125 chatId -1로 고정되는 현상 수정 및 세션 타입 변경
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/templates/EndAgora.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/_components/molecules/LivelyAgoraList.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/login/auth/components/AuthLogin.tsx
  src/app/(main)/user-info/_component/molecules/AccountInfos.tsx
  src/app/(main)/user-info/_component/molecules/ActionButtons.tsx
  src/lib/accessMessageConfig.ts
  src/utils/swalAlert.ts
  types/next-auth.d.ts
Labels: Priority: Urgent, fix

#126 fix: signOut에 redirect 속성 추가
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/utils/ServiceWorkerErrorHandler.ts
  src/app/(chat)/utils/SocketErrorHandler.ts
  src/hooks/useApiError.ts
  src/serverActions/auth.ts
Labels: Priority: Urgent, fix

#127 dev -> main merge
  public/custom-sw.js
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/templates/EndAgora.tsx
  src/app/(chat)/_lib/getAgoraUsers.ts
  src/app/(chat)/_lib/getChatMessages.ts
  src/app/(chat)/_lib/getVoteResult.ts
  src/app/(chat)/_lib/patchAgoraEnd.ts
  src/app/(chat)/_lib/patchAgoraImg.ts
  src/app/(chat)/_lib/patchAgoraStart.ts
  src/app/(chat)/_lib/patchAgoraTimeOut.ts
  src/app/(chat)/_lib/patchChatExit.ts
  src/app/(chat)/_lib/postFilterBadWords.ts
  src/app/(chat)/utils/ServiceWorkerErrorHandler.ts
  src/app/(chat)/utils/SocketErrorHandler.ts
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/_components/molecules/LivelyAgoraList.tsx
  src/app/(main)/_lib/getAgoraCategorySearch.ts
  src/app/(main)/_lib/getAgoraKeywordSearch.ts
  src/app/(main)/_lib/getAgoraTitle.ts
  src/app/(main)/_lib/getLivelyAgora.ts
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/(main)/layout.tsx
  src/app/(main)/login/auth/components/AuthLogin.tsx
  src/app/(main)/page.tsx
  src/app/(main)/user-info/_component/molecules/AccountInfos.tsx
  src/app/(main)/user-info/_component/molecules/ActionButtons.tsx
  src/app/(main)/user-info/_component/organisms/UserInfoMain.tsx
  src/app/(main)/user-info/page.tsx
  src/constants/responseErrorMessage.ts
  src/hooks/useApiError.ts
  src/lib/accessMessageConfig.ts
  src/middleware.ts
  src/serverActions/auth.ts
  src/utils/swalAlert.ts
  types/next-auth.d.ts
Labels: Type: Enhancement, Type: Maintenance, Priority: Urgent, chore, refactor, fix

#129 import 파일 경로 수정
  src/app/(main)/login/auth/components/AuthLogin.tsx
Labels: Priority: Urgent, fix

#130 service-worker workbox 적용
  .eslintrc.json
  public/custom-sw.js
  public/manifest.json
  public/offline.html
  src/middleware.ts
Labels: Type: Maintenance, Priority: Medium, refactor

#132 배포 시 발생한 prettier 에러 수정
  src/app/(chat)/_components/templates/EndAgora.tsx
Labels: Priority: High, fix

#133 dev -> main 병합
  src/app/(chat)/_components/templates/EndAgora.tsx
Labels: Priority: High, fix

#134 pwabuilder 이미지 not found 오류 해결
  public/img/icons/icon-512x512-any.png
Labels: Priority: High, fix

#136 다크모드 색상 변경 및 모바일에서의 텍스트 크기 조정
  public/manifest.json
  src/app/(chat)/_components/atoms/ChatNotification.tsx
  src/app/(chat)/_components/atoms/DiscussionTimer.tsx
  src/app/(chat)/_components/atoms/MyMessage.tsx
  src/app/(chat)/_components/atoms/UserAccessNotification.tsx
  src/app/(chat)/_components/atoms/YourMessage.tsx
  src/app/(chat)/_components/molecules/AgoraInfo.tsx
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/molecules/ChatSideModule.tsx
  src/app/(chat)/_components/molecules/DiscussionStatus.tsx
  src/app/(chat)/_components/molecules/ShareButton.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/MobileNavLink.tsx
  src/app/(main)/_components/atoms/ModalPositionSelectBtn.tsx
  src/app/(main)/_components/molecules/AgoraListDecider.tsx
  src/app/(main)/_components/molecules/LivelyAgoraList.tsx
  src/app/(main)/_components/molecules/NavLinks.tsx
  src/app/(main)/_components/organisms/NavMenu.tsx
  src/app/(main)/create-agora/loading.tsx
  src/app/(main)/flow/enter-agora/_components/SelectedProfile.tsx
  src/app/(main)/login/auth/components/AuthLogin.tsx
  src/app/_components/atoms/loading.tsx
  src/assets/icons/BoltIcon.tsx
  src/store/darkMode.ts
  tailwind.config.ts
Labels: Type: Maintenance, Priority: Medium, refactor

#137 dev -> main 병합
  public/manifest.json
  src/app/(chat)/_components/atoms/ChatNotification.tsx
  src/app/(chat)/_components/atoms/DiscussionTimer.tsx
  src/app/(chat)/_components/atoms/MyMessage.tsx
  src/app/(chat)/_components/atoms/UserAccessNotification.tsx
  src/app/(chat)/_components/atoms/YourMessage.tsx
  src/app/(chat)/_components/molecules/AgoraInfo.tsx
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/molecules/ChatSideModule.tsx
  src/app/(chat)/_components/molecules/DiscussionStatus.tsx
  src/app/(chat)/_components/molecules/ShareButton.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/MobileNavLink.tsx
  src/app/(main)/_components/atoms/ModalPositionSelectBtn.tsx
  src/app/(main)/_components/molecules/AgoraListDecider.tsx
  src/app/(main)/_components/molecules/LivelyAgoraList.tsx
  src/app/(main)/_components/molecules/NavLinks.tsx
  src/app/(main)/_components/organisms/NavMenu.tsx
  src/app/(main)/create-agora/loading.tsx
  src/app/(main)/flow/enter-agora/_components/SelectedProfile.tsx
  src/app/(main)/login/auth/components/AuthLogin.tsx
  src/app/_components/atoms/loading.tsx
  src/assets/icons/BoltIcon.tsx
  src/store/darkMode.ts
  tailwind.config.ts
Labels: Type: Maintenance, Priority: Medium, refactor
