Repository Attica-org/athens-client, pull requests merged in 2024-09, with the labels that each got.

#85 종료 아고라 그래프 표현, 인기 아고라 구현
  src/app/(chat)/_components/organisms/MessageContainer.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/ClosedAgoraVoteResultBar.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_components/molecules/AgoraListDecider.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/_components/molecules/LivelyAgoraList.tsx
  src/app/(main)/_components/organisms/AgoraListDeciderHydration.tsx
  src/app/(main)/_components/templates/Main.tsx
  src/app/(main)/_lib/getLivelyAgora.ts
  src/app/_components/molecules/AgoraImageUpload.tsx
  src/app/model/Agora.ts
Labels: Type: Enhancement, Status: In Progress, Priority: High, feat

#88 MVP2 버그 수정
  src/app/(chat)/_components/atoms/MyMessage.tsx
  src/app/(chat)/_components/atoms/YourMessage.tsx
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(chat)/_components/templates/AgoraSideBar.tsx
  src/app/(main)/_components/atoms/AgoraStatusTab.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/ClosedAgoraVoteResultBar.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_components/atoms/ModalPositionSelectBtn.tsx
  src/app/(main)/_components/atoms/NavIconDecider.tsx
  src/app/(main)/_components/atoms/NoAgoraMessage.tsx
  src/app/(main)/_components/atoms/SearchBar.tsx
  src/app/(main)/_components/atoms/VirtuosoGridCustomList.tsx
  src/app/(main)/_components/molecules/AgoraListDecider.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/_components/molecules/CategoryButtonList.tsx
  src/app/(main)/_components/molecules/LivelyAgoraList.tsx
  src/app/(main)/_components/molecules/NavLinks.tsx
  src/app/(main)/_components/molecules/SelectAgoraColor.tsx
  src/app/(main)/_components/organisms/NavMenu.tsx
  src/app/(main)/_lib/getAgoraTitle.ts
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
  src/app/(main)/flow/enter-agora/_components/EnterAgoraButton.tsx
  src/app/(main)/flow/enter-agora/_components/SelectedProfile.tsx
  src/app/(main)/page.tsx
  src/app/_components/atoms/BackButton.tsx
  src/app/_components/atoms/UserImage.tsx
  src/app/_components/molecules/AgoraImageUpload.tsx
  src/app/_components/molecules/ModalBase.tsx
  src/app/_components/molecules/SNSLogin.tsx
  src/app/error.tsx
  src/app/layout.tsx
  src/app/model/Agora.ts
  src/app/not-found.tsx
  src/assets/icons/addIcon.tsx
  src/assets/icons/homeIcon.tsx
  src/constants/segmentKey.ts
  src/store/create.ts
Labels: Type: Maintenance, Status: In Progress, refactor

#89 fix: 버전 충돌로 인한 에러 해결
  package.json
  public/mockServiceWorker.js
  src/app/(main)/_components/molecules/AgoraListDecider.tsx
  yarn.lock
Labels: Type: Bug, Priority: High, fix

#90 fix: 배포 환경 발생 에러 수정
  package.json
  src/app/_components/atoms/BackButton.tsx
  yarn.lock
Labels: Type: Bug, Priority: High, fix

#92 Chore : 리드미 작성
  README.md
Labels: Status: Done, Priority: Low, chore

#93 EmojiModal UI, 뒤로가기 모달 API 호출
  .gitignore
  package.json
  src/app/(chat)/_components/atoms/EmojiModal.tsx
  src/app/(chat)/_components/atoms/MyMessage.tsx
  src/app/(chat)/_components/atoms/TextHoverMenu.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/organisms/MessageContainer.tsx
  src/app/(main)/_components/atoms/KickedUserAlert.tsx
  src/app/_components/atoms/BackButton.tsx
  src/app/globals.css
  src/assets/icons/DislikeIcon.tsx
  src/assets/icons/HappyIcon.tsx
  src/assets/icons/HeartIcon.tsx
  src/assets/icons/LikeIcon.tsx
  src/assets/icons/LoveIcon.tsx
  src/assets/icons/SadIcon.tsx
  src/hooks/useIsEmojiSendable.ts
  yarn.lock
Labels: Status: Done, Type: Enhancement, Priority: High, feat
