Repository Attica-org/athens-client, pull requests merged in 2024-07, with the labels that each got.

#63 #[62] 토론 종료시 유저 목록 초기화, 종료된 아고라 키워드 검색 후 입장시 모달 거치지 않도록 수정
  src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
  src/app/(main)/_components/atoms/SearchAgora.tsx
Labels: Status: Done, Type: Maintenance, Priority: High, fix

#64 service worker 상태 변화 감지 및 재등록
  src/app/(chat)/_components/templates/EndAgora.tsx
  src/app/(main)/_components/atoms/Agora.tsx
  src/app/(main)/_components/molecules/AgoraList.tsx
  src/app/(main)/_lib/getAgoraCategorySearch.ts
  src/app/_components/utils/ServiceWorkerRegistration.tsx
  src/app/model/Agora.ts
  src/assets/icons/ArrowDownIcon.tsx
Labels: Type: Maintenance, Priority: High, fix

#65 [#62] Fix: 토큰 재발급 토큰 미저장 문제 해결
  src/lib/fetchWrapper.ts
Labels: Status: Done, Type: Maintenance, Priority: High, fix

#67 QA2에서 발견한 서비스워커, 채팅방 문제
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/agoras/[agora]/layout.tsx
  src/app/(main)/_components/atoms/SearchAgora.tsx
  src/app/_components/utils/ServiceWorkerRegistration.tsx
  src/utils/showToast.ts
Labels: Type: Maintenance, Priority: High, fix

#68 refactor: 메인 페이지 atoms 폴더 제외한 컴포넌트 파일 리팩토링
  src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_lib/getAgoraUsers.ts
  src/app/(main)/_components/atoms/ControlNumberInput.tsx
  src/app/(main)/_components/molecules/AgoraListDecider.tsx
  src/app/(main)/_components/molecules/AgoraStatusTabSuspense.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/_components/molecules/CategoryButtonList.tsx
  src/app/(main)/_components/molecules/DiscussionDurationSetter.tsx
  src/app/(main)/_components/molecules/KeywordAgoraList.tsx
  src/app/(main)/_components/molecules/ParticipantCapacitySetter.tsx
  src/app/(main)/_components/molecules/SelectAgoraColor.tsx
  src/app/(main)/_components/organisms/AgoraListDeciderSuspense.tsx
  src/app/(main)/_components/organisms/CategoryButtonContainer.tsx
  src/app/(main)/_components/organisms/EnterAgoraContent.tsx
  src/app/(main)/_components/templates/Main.tsx
  src/app/(main)/create-agora/page.tsx
  src/app/(main)/flow/enter-agora/_components/EnterAgoraButton.tsx
  src/app/(main)/home/layout.tsx
  src/app/(main)/home/page.tsx
  src/app/_components/utils/ServiceWorkerRegistration.tsx
  src/app/model/Agora.ts
  src/app/model/AgoraUser.ts
  src/constants/agoraCategory.ts
  src/utils/tokenManager.ts
Labels: Type: Maintenance, Status: In Progress, Priority: Medium, refactor

#69 메인페이지 atoms 폴더 리팩토링
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/ControlNumberInput.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_components/atoms/ModalPositionSelectBtn.tsx
  src/app/(main)/_components/atoms/SearchBar.tsx
  src/app/(main)/_components/molecules/PageTitle.tsx
  src/app/(main)/create-agora/layout.tsx
  src/app/(main)/flow/enter-agora/_components/ModalPosSelectContainer.tsx
  src/app/(main)/home/layout.tsx
  src/app/_components/utils/isActiveAgora.ts
  src/app/model/Agora.ts
Labels: Type: Maintenance, Status: In Progress, Priority: Medium, refactor

#72 공통 컴포넌트 리팩토링
  src/app/(chat)/_components/organisms/AgoraUserSide.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/templates/EndAgora.tsx
  src/app/(chat)/_components/templates/ResultAgora.tsx
  src/app/(chat)/_components/templates/SocialShare.tsx
  src/app/(main)/_components/atoms/AgoraPointColor.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_components/templates/EnterAgora.tsx
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
  src/app/_components/atoms/BackButton.tsx
  src/app/_components/atoms/CloseButton.tsx
  src/app/_components/atoms/UserImage.tsx
  src/app/_components/molecules/ModalBase.tsx
  src/app/_components/utils/Confetti.tsx
  src/app/_components/utils/NetworkErrorNotification.tsx
  src/app/_components/utils/RQProvider.tsx
  src/constants/agoraCategory.ts
  src/hooks/useNetworkStatus.ts
  src/hooks/useVote.tsx
  src/middleware.ts
  src/store/create.ts
  src/utils/indexedDB.ts
  src/utils/isActiveAgora.ts
  src/utils/showToast.ts
  src/utils/swManager.ts
  tsconfig.json
Labels: Type: Maintenance, Priority: Medium, refactor

#73 [#66] Refactor : 중복되는 타입 통합
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/model/Agora.ts
Labels: Type: Maintenance, Priority: Medium, refactor

#74 리팩토링 및 아고라 생성 버그 수정
  package.json
  src/app/(chat)/_components/templates/ResultAgora.tsx
  src/app/(chat)/agoras/[agora]/layout.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/DesktopNavLink.tsx
  src/app/(main)/_components/atoms/MobileNavLink.tsx
  src/app/(main)/_components/molecules/CategoryButtonList.tsx
  src/app/(main)/_components/organisms/NavMenu.tsx
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
  src/app/_components/molecules/ModalBase.tsx
  src/app/config/MSWComponent.tsx
  src/app/config/RQProvider.tsx
  src/app/config/ServiceWorkerRegistration.tsx
  src/app/config/ToasterContainer.tsx
  src/app/globals.css
  src/app/layout.tsx
  yarn.lock
Labels: Type: Maintenance, Priority: Medium, refactor

#75 Chat atoms, molecules 리팩토링
  src/app/(chat)/_components/atoms/DiscussionTimer.tsx
  src/app/(chat)/_components/atoms/SocialShareLogos.tsx
  src/app/(chat)/_components/atoms/VoteResult.tsx
  src/app/(chat)/_components/molecules/AgoraInfo.tsx
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/molecules/DiscussionStatus.tsx
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/globals.css
Labels: Type: Maintenance, Priority: Medium, refactor

#76 [#66] 리팩토링
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/templates/EndAgora.tsx
Labels: Type: Maintenance, Status: In Progress, Priority: Medium, refactor
