Repository Attica-org/athens-client, pull requests merged in 2024-10, with the labels that each got.

#97 [#94], [#95] 일부 해결 및, 병합 수행
  next.config.js
  package.json
  public/custom-sw.js
  src/app/(chat)/_components/atoms/EmojiModal.tsx
  src/app/(chat)/_components/atoms/Emojis.tsx
  src/app/(chat)/_components/atoms/MyMessage.tsx
  src/app/(chat)/_components/atoms/TextHoverMenu.tsx
  src/app/(chat)/_components/atoms/UserReaction.tsx
  src/app/(chat)/_components/atoms/VoteResult.tsx
  src/app/(chat)/_components/atoms/YourMessage.tsx
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
  src/app/(chat)/_components/organisms/ErrorBoundaryMessage.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/organisms/MessageContainer.tsx
  src/app/(chat)/_lib/getAgoraUsers.ts
  src/app/(chat)/_lib/getChatMessages.ts
  src/app/(chat)/_lib/getVoteResult.ts
  src/app/(chat)/_lib/patchChatExit.ts
  src/app/(chat)/_lib/postFilterBadWords.ts
  src/app/(chat)/agoras/[agora]/page.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/_components/molecules/KeywordAgoraList.tsx
  src/app/(main)/_components/organisms/AgoraListDeciderHydration.tsx
  src/app/(main)/_components/organisms/EnterAgoraContent.tsx
  src/app/(main)/_lib/getAgoraTitle.ts
  src/app/(main)/user-info/_component/atoms/AccountInfo.tsx
  src/app/(main)/user-info/_component/atoms/ActionButton.tsx
  src/app/(main)/user-info/_component/atoms/Borderline.tsx
  src/app/(main)/user-info/_component/molecules/Header.tsx
  src/app/(main)/user-info/_component/molecules/Main.tsx
  src/app/(main)/user-info/layout.tsx
  src/app/(main)/user-info/page.tsx
  src/app/_components/atoms/BackButton.tsx
  src/app/globals.css
  src/app/model/Agora.ts
  src/app/model/AgoraMeta.ts
  src/constants/queryKey.ts
  src/hooks/useClickOutside.ts
  src/hooks/useIsEmojiSendable.ts
  src/hooks/useTouchHandler.ts
  yarn.lock
Labels: Status: Done, Type: Enhancement, Priority: High, feat

#98 이미지 업로드 데이터 타입 수정 및 채팅방 가상 스크롤 이전 코드로 복구
  .eslintrc.json
  next.config.js
  package.json
  public/mockServiceWorker.js
  src/app/(chat)/_components/atoms/DiscussionTimer.tsx
  src/app/(chat)/_components/atoms/MyMessage.tsx
  src/app/(chat)/_components/atoms/NotificationNewMessage.tsx
  src/app/(chat)/_components/atoms/ScrollToBottomBtn.tsx
  src/app/(chat)/_components/atoms/UserReaction.tsx
  src/app/(chat)/_components/atoms/VoteResult.tsx
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(chat)/_components/molecules/ModifyAgoraImage.tsx
  src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/templates/AgoraSideBar.tsx
  src/app/(chat)/_components/templates/ResultAgora.tsx
  src/app/(chat)/_lib/patchAgoraImg.ts
  src/app/(main)/_components/atoms/AgoraStatusTab.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_components/molecules/AgoraListDecider.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/_components/molecules/KeywordAgoraList.tsx
  src/app/(main)/_components/molecules/LivelyAgoraList.tsx
  src/app/(main)/_components/organisms/EnterAgoraContent.tsx
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
  src/app/(main)/create-agora/_component/CreateAgoraImageUpload.tsx
  src/app/(main)/create-agora/page.tsx
  src/app/(main)/flow/enter-agora/_components/EnterAgoraButton.tsx
  src/app/(main)/flow/enter-agora/_components/SetUserProfile.tsx
  src/app/(main)/page.tsx
  src/app/_components/_lib/OAuthRequest.ts
  src/app/_components/atoms/ImageCropper.tsx
  src/app/_components/molecules/AgoraImageUpload.tsx
  src/app/_components/molecules/SNSLogin.tsx
  src/app/model/Agora.ts
  src/assets/icons/ArrowDownIcon.tsx
  src/lib/fetchWrapper.ts
  src/lib/getMemberToken.ts
  src/store/agora.ts
  src/store/create.ts
  src/store/search.ts
  src/utils/base64ToFile.ts
  src/utils/unloadDisconnectSocket.ts
  yarn.lock
Labels: Status: Done, Type: Enhancement, Type: Maintenance, Priority: Medium, feat, fix

#99 fix: 배포시 발생한 async await 오류 수정
  src/app/_components/_lib/OAuthRequest.ts
Labels: Type: Maintenance, Priority: Urgent, fix

#100 Fix : 종료된 아고라 exit api 호출 안하도록 변경
  src/app/(chat)/_components/organisms/Header.tsx
Labels: Type: Bug, Priority: Urgent, fix

#101 fix: 채팅방에서 messages.length 출력되는 문제 수정
  src/app/(chat)/_components/molecules/Message.tsx
Labels: Type: Bug, Priority: Urgent, fix

#103 [#95] 채팅 반응하기 기능 구현
  src/app/(chat)/_components/atoms/ChatNotification.tsx
  src/app/(chat)/_components/atoms/DiscussionTimer.tsx
  src/app/(chat)/_components/atoms/EmojiModal.tsx
  src/app/(chat)/_components/atoms/MyMessage.tsx
  src/app/(chat)/_components/atoms/ReactionMenuButton.tsx
  src/app/(chat)/_components/atoms/UserReaction.tsx
  src/app/(chat)/_components/atoms/VoteResult.tsx
  src/app/(chat)/_components/atoms/YourMessage.tsx
  src/app/(chat)/_components/molecules/DiscussionStatus.tsx
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/templates/AgoraSideBar.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
  src/app/(main)/flow/enter-agora/_components/EnterAgoraButton.tsx
  src/app/model/Agora.ts
  src/app/model/Message.ts
  src/app/model/Reaction.ts
  src/constants/Agora.ts
  src/constants/queryKey.ts
  src/hooks/useIsEmojiSendable.ts
  tailwind.config.ts
Labels: Status: Done, Type: Enhancement, Type: Maintenance, Priority: High, feat, fix

#105 Auth 사용하여 소셜 로그인으로 받아온 토큰 관리
  next.config.js
  package.json
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/templates/AgoraSideBar.tsx
  src/app/(chat)/_lib/getAgoraUsers.ts
  src/app/(chat)/_lib/getChatMessages.ts
  src/app/(chat)/_lib/getVoteResult.ts
  src/app/(chat)/_lib/patchAgoraEnd.ts
  src/app/(chat)/_lib/patchAgoraImg.ts
  src/app/(chat)/_lib/patchAgoraStart.ts
  src/app/(chat)/_lib/patchAgoraTimeOut.ts
  src/app/(chat)/_lib/patchChatExit.ts
  src/app/(chat)/_lib/postFilterBadWords.ts
  src/app/(chat)/agoras/[agora]/page.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_components/atoms/KickedUserAlert.tsx
  src/app/(main)/_components/organisms/EnterAgoraContent.tsx
  src/app/(main)/_components/templates/SignIn.tsx
  src/app/(main)/_lib/getAgoraCategorySearch.ts
  src/app/(main)/_lib/getAgoraKeywordSearch.ts
  src/app/(main)/_lib/getAgoraTitle.ts
  src/app/(main)/_lib/getLivelyAgora.ts
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/(main)/login/auth/page.tsx
  src/app/(main)/login/route.ts
  src/app/(main)/page.tsx
  src/app/_components/_lib/OAuthRequest.ts
  src/app/_components/molecules/SNSLogin.tsx
  src/app/_components/utils/AuthSession.tsx
  src/app/_components/utils/UnloadDisconnectSocket.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/auth.config.ts
  src/auth.ts
  src/constants/AuthErrorMessage.ts
  src/lib/fetchWrapper.ts
  src/lib/getAgoras.ts
  src/lib/getMemberToken.ts
  src/lib/getReissuanceToken.ts
  src/serverActions/auth.ts
  src/utils/swalAlert.ts
  src/utils/unloadDisconnectSocket.ts
  src/utils/validate.ts
  types/next-auth.d.ts
  yarn.lock
Labels: Type: Enhancement, Status: In Progress, Priority: High, feat

#107 vercel 배포 환경 auth 에러
  src/app/(main)/login/auth/components/AuthLogin.tsx
  src/app/(main)/login/auth/page.tsx
  src/auth.config.ts
  src/middleware.ts
Labels: Priority: High, refactor, fix
