Repository Attica-org/athens-client, pull requests merged in 2025-03, with the labels that each got.

#178 첫 렌더링 후 meta로 테마 설정 추가
  src/app/_components/utils/SetTheme.tsx
  src/app/layout.tsx
Labels: Type: Enhancement, Priority: Medium, refactor

#179 첫 렌더링 후 meta 태그로 테마 설정 추가 dev -> main
  src/app/_components/utils/SetTheme.tsx
  src/app/layout.tsx
Labels: Type: Enhancement, Priority: Medium, refactor

#180 종료/활성화 채팅방에서의 새로고침 시 자동 재입장 되도록 로직 수정
  src/app/(chat)/_components/atoms/ChatPageLoading.tsx
  src/app/(chat)/_components/atoms/HamburgerButton.tsx
  src/app/(chat)/_components/atoms/ShareButton.tsx
  src/app/(chat)/_components/molecules/MenuItems.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_lib/getAgoraTitle.ts
  src/app/(main)/login/route.ts
  src/app/(main)/page.tsx
  src/app/(main)/user-info/_lib/postLogout.ts
  src/app/_components/utils/SessionNavigationObserver.tsx
  src/app/_components/utils/SetChatInfoReset.tsx
  src/app/config/ChatPageLoadConfig.tsx
  src/app/layout.tsx
  src/app/model/Agora.ts
  src/constants/segmentKey.ts
  src/hooks/useApiError.ts
  src/hooks/usePreviousPage.ts
  src/hooks/useUnloadDisconnectSocket.tsx
  src/hooks/useUpdateSession.ts
  src/store/agora.ts
Labels: Type: Bug, Priority: High, fix

#181 종료/활성화 채팅방에서의 새로고침 시 자동 재입장 되도록 로직 수정 dev -> main
  src/app/(chat)/_components/atoms/ChatPageLoading.tsx
  src/app/(chat)/_components/atoms/HamburgerButton.tsx
  src/app/(chat)/_components/atoms/ShareButton.tsx
  src/app/(chat)/_components/molecules/MenuItems.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_lib/getAgoraTitle.ts
  src/app/(main)/login/route.ts
  src/app/(main)/page.tsx
  src/app/(main)/user-info/_lib/postLogout.ts
  src/app/_components/utils/SessionNavigationObserver.tsx
  src/app/_components/utils/SetChatInfoReset.tsx
  src/app/config/ChatPageLoadConfig.tsx
  src/app/layout.tsx
  src/app/model/Agora.ts
  src/constants/segmentKey.ts
  src/hooks/useApiError.ts
  src/hooks/usePreviousPage.ts
  src/hooks/useUnloadDisconnectSocket.tsx
  src/hooks/useUpdateSession.ts
  src/store/agora.ts
Labels: Type: Bug, Priority: High, fix

#182 채팅방 소켓 인증 에러 확인을 위해 세션 전달
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/utils/SocketErrorHandler.ts
Labels: Type: Maintenance, Priority: High, fix

#183 채팅방 소켓 인증 에러 확인을 위해 세션 전달 dev -> main (#182)
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/utils/SocketErrorHandler.ts
Labels: Type: Maintenance, Priority: High, fix

#184 채팅방을 나갈 때, 상태 reset을 한 번에 관리하도록 변경, 강퇴 당한 사용자가 퇴장할 때 상태를 초기화하도록 수정
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/utils/resetStateOnChatExit.ts
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
  src/app/_components/molecules/ImageCropper.tsx
  src/hooks/useUnloadDisconnectSocket.tsx
  src/store/chatInfo.ts
  src/store/uploadImage.ts
Labels: Type: Maintenance, Priority: High, refactor, fix

#188 QA에서 발견된 버그 수정사항 적용
  src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_lib/getAgoraUsers.ts
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_lib/postEnterClosedAgora.ts
  src/app/model/Agora.ts
Labels: Type: Bug, Priority: High, fix

#189 QA에서 발견된 버그 수정사항 적용 dev -> main
  src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_lib/getAgoraUsers.ts
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_lib/postEnterClosedAgora.ts
  src/app/model/Agora.ts
Labels: Type: Bug, Priority: High, fix

#190 강제 퇴장 동작 및 채팅 반응 로직 수정
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_lib/postKickVote.ts
Labels: Type: Maintenance, Priority: High, refactor

#192 아고라 생성시 크롭 이미지 크기로 세션 용량 초과 문제 수정
  .yarnrc.yml
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/create-agora/_component/CreateAgoraImageUpload.tsx
  src/app/_components/molecules/ImageCropper.tsx
  src/utils/convertBase64ToBlobUrl.ts
  src/utils/getCroppedImg.ts
Labels: Type: Bug, Priority: High, fix

#193 아고라 생성시 크롭 이미지 크기로 세션 용량 초과 문제 수정 dev -> main
  .yarnrc.yml
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/create-agora/_component/CreateAgoraImageUpload.tsx
  src/app/_components/molecules/ImageCropper.tsx
  src/utils/convertBase64ToBlobUrl.ts
  src/utils/getCroppedImg.ts
Labels: Type: Bug, Priority: High, fix
