Repository Attica-org/athens-client, pull requests merged in 2025-01, with the labels that each got.

#142 로그아웃시 api 호출 기능 구현, 리렌더링 문제 해결, 리팩토링
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(main)/_components/molecules/CategoryButtonList.tsx
  src/app/(main)/_components/organisms/EnterAgoraContent.tsx
  src/app/(main)/create-agora/_component/AgoraTitleInput.tsx
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
  src/app/(main)/flow/enter-agora/_components/EnterAgoraButton.tsx
  src/app/(main)/flow/enter-agora/_components/SelectProfile.tsx
  src/app/(main)/flow/enter-agora/_components/SetUserProfile.tsx
  src/app/(main)/user-info/_component/molecules/ActionButtons.tsx
  src/app/(main)/user-info/_lib/postLogout.ts
  src/constants/responseErrorMessage.ts
Labels: Type: Enhancement, Type: Maintenance, Priority: High, feat, refactor

#143 웹소켓 연결 로직 변경, 탈퇴하기 기능, 유저 강퇴 기능 구현
  package-lock.json
  src/app/(chat)/_components/atoms/EmojiModal.tsx
  src/app/(chat)/_components/atoms/MyMessage.tsx
  src/app/(chat)/_components/atoms/YourMessage.tsx
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
  src/app/(chat)/_components/organisms/ErrorBoundaryMessage.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_lib/postKickVote.ts
  src/app/(main)/create-agora/_component/AgoraTitleInput.tsx
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
  src/app/(main)/flow/enter-agora/_components/EnterAgoraButton.tsx
  src/app/(main)/user-info/_component/molecules/ActionButtons.tsx
  src/app/(main)/user-info/_lib/deleteUserAccount.ts
  src/app/(main)/user-info/_lib/postLogout.ts
  src/app/globals.css
  src/app/model/Agora.ts
  src/constants/responseErrorMessage.ts
  src/hooks/useUnloadDisconnectSocket.tsx
  src/store/agora.ts
  src/store/chatInfo.ts
  src/store/webSocket.ts
  src/utils/swalAlert.ts
Labels: Status: Done, Type: Enhancement, Type: Maintenance, Priority: Urgent, feat, fix

#144 가상스크롤 로직 변경 및 홈 버그 수정
  src/app/(chat)/_components/atoms/ChatNotification.tsx
  src/app/(chat)/_components/atoms/NotificationNewMessage.tsx
  src/app/(chat)/_components/atoms/ScrollToBottomBtn.tsx
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_lib/getChatMessages.ts
  src/app/(chat)/_lib/getChatMessagesServer.ts
  src/app/(chat)/agoras/[agora]/page.tsx
  src/app/(main)/_components/atoms/AgoraStatusTab.tsx
  src/app/(main)/_components/atoms/CategoryAgoraNowTitle.tsx
  src/app/(main)/_components/organisms/CategoryButtonContainer.tsx
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
  src/app/(main)/login/auth/components/AuthLogin.tsx
  src/app/_components/organisms/AgoraImageUpload.tsx
  src/constants/queryKey.ts
  src/utils/swalAlert.ts
  tailwind.config.ts
Labels: Type: Bug, Priority: Medium, feat, fix

#146 fix: 카테고리 아고라 입장시 userId 설정해주지 않는 문제 해결
  src/app/(main)/_components/atoms/CategoryAgora.tsx
Labels: Type: Bug, Type: Maintenance, Priority: Urgent, fix

#148 fix : userId를 받지 않았을 경우 default 값으로 0으로 설정
  src/store/agora.ts
Labels: Type: Bug, Type: Maintenance, Priority: Urgent, fix

#150 fix: Props 설정 변경
  src/app/(main)/user-info/_component/molecules/ActionButtons.tsx
  src/app/(main)/user-info/_lib/deleteUserAccount.ts
Labels: Priority: Urgent, fix

#152 docs: README 수정
  README.md
Labels: chore

#153 Readme 수정 dev -> main
  README.md
Labels: chore

#154 종료된 아고라에 유저 인증 로직 추가
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_components/atoms/NoAgoraMessage.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/_components/molecules/LivelyAgoraList.tsx
  src/app/(main)/_components/templates/Main.tsx
  src/app/(main)/_components/templates/SignIn.tsx
  src/app/(main)/_lib/getEnterClosedAgoraStatus.ts
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/_components/atoms/loading.tsx
  src/app/_components/molecules/SNSLogin.tsx
  src/auth.config.ts
  src/constants/queryKey.ts
  src/constants/responseErrorMessage.ts
Labels: Type: Enhancement, Priority: Medium, feat

#155 종료된 아고라 인증 로직 추가 PR dev -> main
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_components/atoms/NoAgoraMessage.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/_components/molecules/LivelyAgoraList.tsx
  src/app/(main)/_components/templates/Main.tsx
  src/app/(main)/_components/templates/SignIn.tsx
  src/app/(main)/_lib/getEnterClosedAgoraStatus.ts
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/_components/atoms/loading.tsx
  src/app/_components/molecules/SNSLogin.tsx
  src/auth.config.ts
  src/constants/queryKey.ts
  src/constants/responseErrorMessage.ts
Labels: Type: Enhancement, Priority: Medium, feat

#157 아고라 생성하기 버튼 잘리는 문제 수정 dev -> main
  src/app/(main)/create-agora/page.tsx
Labels: Type: Bug, Priority: Urgent, fix

#158 manifest 테마 색상에 맞춰 color 값 변경
  public/manifest.json
  src/app/layout.tsx
Labels: Type: Maintenance, Priority: Low, refactor

#159 dev -> main
  public/manifest.json
  src/app/layout.tsx
Labels: Type: Maintenance, refactor
