Repository Attica-org/athens-client, pull requests merged in 2025-04, with the labels that each got.

#194 로그인 없이 채팅방 접근시 callbackUrl 추가하여 로그인 후 redirect 하도록 수정
  src/app/(main)/_components/templates/SignIn.tsx
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/login/auth/components/AuthLogin.tsx
  src/app/(main)/login/auth/page.tsx
  src/app/(main)/login/route.ts
  src/app/(main)/page.tsx
  src/app/_components/molecules/SNSLogin.tsx
  src/app/config/ChatPageLoadConfig.tsx
  src/constants/responseErrorMessage.ts
  src/middleware.ts
Labels: Type: Bug, Priority: High, fix

#195 로그인 없이 채팅방 접근시 callbackUrl 추가하여 로그인 후 redirect 하도록 수정 dev -> main
  src/app/(main)/_components/templates/SignIn.tsx
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/login/auth/components/AuthLogin.tsx
  src/app/(main)/login/auth/page.tsx
  src/app/(main)/login/route.ts
  src/app/(main)/page.tsx
  src/app/_components/molecules/SNSLogin.tsx
  src/app/config/ChatPageLoadConfig.tsx
  src/constants/responseErrorMessage.ts
  src/middleware.ts
Labels: Type: Bug, Priority: High, fix

#196 채팅방에서 강퇴된 인원이 이후 강퇴 투표의 과반수 계산에 포함되는 문제를 수정
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
  src/app/_components/utils/SetChatInfoReset.tsx
  src/utils/swalAlert.ts
Labels: Priority: Urgent, refactor, fix

#198 이미지 없이 채팅방 생성시 파일 형태로 전달하지 않으면 발생하는 에러 수정
  src/app/(main)/_lib/postCreateAgora.ts
Labels: Type: Bug, Priority: High, fix

#199 Dev -> main
  src/app/(main)/_lib/postCreateAgora.ts
Labels: Priority: Urgent, fix

#203 채팅방 뒤로가기 문제 및 서버 응답 이미지 프로퍼티 key 수정
  src/app/(chat)/_components/molecules/ModifyAgoraImage.tsx
  src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
  src/app/(chat)/_components/templates/AgoraSideBar.tsx
  src/app/(chat)/utils/resetStateOnChatExit.ts
  src/app/config/ChatPageLoadConfig.tsx
  src/app/model/Agora.ts
  src/store/agora.ts
  src/utils/validation/validateImage.ts
Labels: Type: Bug, Priority: High, fix

#204 채팅방 뒤로가기 문제 및 서버 응답 이미지 프로퍼티 key 수정 dev -> main
  src/app/(chat)/_components/molecules/ModifyAgoraImage.tsx
  src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
  src/app/(chat)/_components/templates/AgoraSideBar.tsx
  src/app/(chat)/utils/resetStateOnChatExit.ts
  src/app/config/ChatPageLoadConfig.tsx
  src/app/model/Agora.ts
  src/store/agora.ts
  src/utils/validation/validateImage.ts
Labels: Type: Bug, Priority: High, fix

#206 채팅방 유저 강퇴시 다른 사용자들에게 강퇴 메시지 가도록 구현
  src/app/(chat)/_components/atoms/UserAccessNotification.tsx
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/utils/resetStateOnChatExit.ts
  src/app/(chat)/utils/updateUserAccessMessage.tsx
  src/app/_components/utils/SetChatInfoReset.tsx
  src/app/model/AccessStatus.ts
  src/app/model/Agora.ts
  src/app/model/Message.ts
  src/store/kickedUser.ts
Labels: Type: Enhancement, Type: Maintenance, Priority: Urgent, feat, refactor

#208 fix: import 에러 수정
  src/app/(chat)/utils/updateUserAccessMessage.tsx
Labels: Priority: Urgent, fix
