Repository Attica-org/athens-client, pull requests merged in 2025-05, with the labels that each got.

#210 채팅방 웹 접근성 개선 (키보드 이벤트 및 SR)
  src/app/(chat)/_components/atoms/ChatNotification.tsx
  src/app/(chat)/_components/atoms/DiscussionTimer.tsx
  src/app/(chat)/_components/atoms/EmojiModal.tsx
  src/app/(chat)/_components/atoms/HamburgerButton.tsx
  src/app/(chat)/_components/atoms/MyMessage.tsx
  src/app/(chat)/_components/atoms/NotificationNewMessage.tsx
  src/app/(chat)/_components/atoms/ObserverStatus.tsx
  src/app/(chat)/_components/atoms/ScrollToBottomBtn.tsx
  src/app/(chat)/_components/atoms/ShareButton.tsx
  src/app/(chat)/_components/atoms/SocialShareLogos.tsx
  src/app/(chat)/_components/atoms/UserAccessNotification.tsx
  src/app/(chat)/_components/atoms/UserReaction.tsx
  src/app/(chat)/_components/atoms/VoteActionButtons.tsx
  src/app/(chat)/_components/atoms/VoteResult.tsx
  src/app/(chat)/_components/atoms/VoteResultLoader.tsx
  src/app/(chat)/_components/atoms/VoteTimer.tsx
  src/app/(chat)/_components/atoms/YourMessage.tsx
  src/app/(chat)/_components/molecules/AgoraInfo.tsx
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/molecules/ChatSideModule.tsx
  src/app/(chat)/_components/molecules/DiscussionStatus.tsx
  src/app/(chat)/_components/molecules/MenuItems.tsx
  src/app/(chat)/_components/molecules/MessageItem.tsx
  src/app/(chat)/_components/organisms/ErrorBoundaryMessage.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/organisms/Message.tsx
  src/app/(chat)/_components/templates/AgoraSideBar.tsx
  src/app/(chat)/_components/templates/EndAgora.tsx
  src/app/(chat)/_components/templates/MessageContainer.tsx
  src/app/(chat)/_components/templates/ResultAgora.tsx
  src/app/(chat)/agoras/[agora]/page.tsx
  src/app/(chat)/layout.tsx
  src/app/(main)/_components/organisms/EnterAgoraContent.tsx
  src/app/_components/molecules/ModalBase.tsx
  src/app/_components/utils/SetChatInfoReset.tsx
  src/assets/icons/MoreVertIcon.tsx
  src/hooks/useAccessibleMessageNotifier.ts
  src/hooks/useFocusTrap.ts
  src/store/sidebar.ts
  src/utils/swalAlert.ts
Labels: Type: Maintenance, Priority: Medium, refactor

#211 채팅방 SR, 키보드 접근성 개선 dev -> main
  src/app/(chat)/_components/atoms/ChatNotification.tsx
  src/app/(chat)/_components/atoms/DiscussionTimer.tsx
  src/app/(chat)/_components/atoms/EmojiModal.tsx
  src/app/(chat)/_components/atoms/HamburgerButton.tsx
  src/app/(chat)/_components/atoms/MyMessage.tsx
  src/app/(chat)/_components/atoms/NotificationNewMessage.tsx
  src/app/(chat)/_components/atoms/ObserverStatus.tsx
  src/app/(chat)/_components/atoms/ScrollToBottomBtn.tsx
  src/app/(chat)/_components/atoms/ShareButton.tsx
  src/app/(chat)/_components/atoms/SocialShareLogos.tsx
  src/app/(chat)/_components/atoms/UserAccessNotification.tsx
  src/app/(chat)/_components/atoms/UserReaction.tsx
  src/app/(chat)/_components/atoms/VoteActionButtons.tsx
  src/app/(chat)/_components/atoms/VoteResult.tsx
  src/app/(chat)/_components/atoms/VoteResultLoader.tsx
  src/app/(chat)/_components/atoms/VoteTimer.tsx
  src/app/(chat)/_components/atoms/YourMessage.tsx
  src/app/(chat)/_components/molecules/AgoraInfo.tsx
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/molecules/ChatSideModule.tsx
  src/app/(chat)/_components/molecules/DiscussionStatus.tsx
  src/app/(chat)/_components/molecules/MenuItems.tsx
  src/app/(chat)/_components/molecules/MessageItem.tsx
  src/app/(chat)/_components/organisms/ErrorBoundaryMessage.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/_components/organisms/Message.tsx
  src/app/(chat)/_components/templates/AgoraSideBar.tsx
  src/app/(chat)/_components/templates/EndAgora.tsx
  src/app/(chat)/_components/templates/MessageContainer.tsx
  src/app/(chat)/_components/templates/ResultAgora.tsx
  src/app/(chat)/agoras/[agora]/page.tsx
  src/app/(chat)/layout.tsx
  src/app/(main)/_components/organisms/EnterAgoraContent.tsx
  src/app/_components/molecules/ModalBase.tsx
  src/app/_components/utils/SetChatInfoReset.tsx
  src/assets/icons/MoreVertIcon.tsx
  src/hooks/useAccessibleMessageNotifier.ts
  src/hooks/useFocusTrap.ts
  src/store/sidebar.ts
  src/utils/swalAlert.ts
Labels: Type: Maintenance, Priority: Medium, refactor

#213 메인아고라, 아고라 생성, 사용자 정보 페이지 웹 접근성 개선
  src/app/(main)/_components/atoms/AgoraPointColor.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/CategoryAgoraNowTitle.tsx
  src/app/(main)/_components/atoms/ControlNumberInput.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_components/atoms/NoAgoraMessage.tsx
  src/app/(main)/_components/atoms/SearchBar.tsx
  src/app/(main)/_components/atoms/ThemeSwitcher.tsx
  src/app/(main)/_components/molecules/CategoryButtonList.tsx
  src/app/(main)/_components/molecules/DiscussionDurationSetter.tsx
  src/app/(main)/_components/molecules/LivelyAgoraList.tsx
  src/app/(main)/_components/molecules/PageTitle.tsx
  src/app/(main)/_components/molecules/ParticipantCapacitySetter.tsx
  src/app/(main)/_components/molecules/SelectAgoraColor.tsx
  src/app/(main)/_components/organisms/NavMenu.tsx
  src/app/(main)/_components/templates/DesktopNav.tsx
  src/app/(main)/_components/templates/Main.tsx
  src/app/(main)/_components/templates/MobileNav.tsx
  src/app/(main)/create-agora/_component/AgoraTitleInput.tsx
  src/app/(main)/create-agora/page.tsx
  src/app/(main)/flow/enter-agora/_components/SelectProfile.tsx
  src/app/(main)/home/page.tsx
  src/app/(main)/page.tsx
  src/app/(main)/user-info/_component/atoms/AccountInfo.tsx
  src/app/(main)/user-info/_component/atoms/ActionButton.tsx
  src/app/(main)/user-info/page.tsx
  src/app/(main)/utils/getScreenReaderString.ts
  src/app/_components/atoms/ImageCropperHeader.tsx
  src/app/_components/molecules/ImageCropper.tsx
  src/app/_components/organisms/AgoraImageUpload.tsx
  src/app/layout.tsx
  src/app/model/Agora.ts
  src/assets/icons/RemoveIcon.tsx
  tailwind.config.ts
Labels: Type: Maintenance, Priority: Urgent, refactor

#216 공통 타입 폴더 리팩토링
  src/app/(chat)/_components/atoms/EmojiModal.tsx
  src/app/(chat)/_components/atoms/Emojis.tsx
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/molecules/ModifyAgoraImage.tsx
  src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
  src/app/(chat)/_components/templates/AgoraSideBar.tsx
  src/app/(main)/_components/atoms/CategoryAgora.tsx
  src/app/(main)/_components/atoms/ControlNumberInput.tsx
  src/app/(main)/_components/atoms/KeywordAgora.tsx
  src/app/(main)/_components/atoms/ModalPositionSelectBtn.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/_components/molecules/KeywordAgoraList.tsx
  src/app/(main)/_components/molecules/LivelyAgoraList.tsx
  src/app/(main)/_components/molecules/ParticipantCapacitySetter.tsx
  src/app/(main)/_components/organisms/EnterAgoraContent.tsx
  src/app/(main)/_lib/getAgoraCategorySearch.ts
  src/app/(main)/_lib/getAgoraKeywordSearch.ts
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
  src/app/(main)/create-agora/_component/CreateAgoraImageUpload.tsx
  src/app/(main)/flow/enter-agora/_components/EnterAgoraButton.tsx
  src/app/(main)/flow/enter-agora/_components/ModalPosSelectContainer.tsx
  src/app/(main)/utils/getScreenReaderString.ts
  src/app/config/ChatPageLoadConfig.tsx
  src/app/model/Agora.ts
  src/app/model/AgoraMeta.ts
  src/app/model/Category.ts
  src/app/model/Message.ts
  src/app/model/Reaction.ts
  src/constants/consts.ts
  src/store/agora.ts
  src/store/create.ts
  src/store/enter.ts
  src/utils/validation/validateAgora.ts
  src/utils/validation/validateIsActiveAgora.ts
Labels: Type: Maintenance, refactor

#218 Refactor/chat type
  src/app/(chat)/_components/atoms/DiscussionTimer.tsx
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/molecules/DiscussionStatus.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(chat)/_components/organisms/Message.tsx
  src/app/(chat)/_components/templates/AgoraSideBar.tsx
  src/app/(chat)/_components/templates/EndAgora.tsx
  src/app/(chat)/_components/templates/MessageContainer.tsx
  src/app/(chat)/_lib/getAgoraUsers.ts
  src/app/(chat)/_lib/getChatMessages.ts
  src/app/(chat)/_lib/getChatMessagesServer.ts
  src/app/(chat)/_lib/getVoteResult.ts
  src/app/(chat)/_lib/patchAgoraEnd.ts
  src/app/(chat)/_lib/patchAgoraImg.ts
  src/app/(chat)/_lib/patchAgoraStart.ts
  src/app/(chat)/_lib/patchAgoraTimeOut.ts
  src/app/(chat)/_lib/patchChatExit.ts
  src/app/(chat)/_lib/postFilterBadWords.ts
  src/app/(chat)/_lib/postKickVote.ts
  src/app/(chat)/agoras/[agora]/page.tsx
  src/app/(chat)/utils/updateUserAccessMessage.tsx
  src/app/(main)/_lib/getAgoraCategorySearch.ts
  src/app/(main)/_lib/getAgoraKeywordSearch.ts
  src/app/(main)/_lib/getAgoraTitle.ts
  src/app/(main)/_lib/getLivelyAgora.ts
  src/app/(main)/_lib/postCreateAgora.ts
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/(main)/_lib/postEnterClosedAgora.ts
  src/app/(main)/user-info/_lib/deleteUserAccount.ts
  src/app/(main)/user-info/_lib/postLogout.ts
  src/app/model/API.ts
  src/app/model/Agora.ts
  src/app/model/AgoraMeta.ts
  src/app/model/Message.ts
  src/app/model/ServiceWorker.ts
  src/lib/fetchWrapper.ts
  src/lib/getAgoras.ts
  src/lib/getReissuanceToken.ts
Labels: Type: Maintenance, Priority: Medium, refactor
