Repository Attica-org/athens-client, pull requests merged in 2025-02, with the labels that each got.

#161 리드미 병합
  README.md
Labels: chore

#162 update : update demonstration video
  README.md
Labels: chore

#163 dev -> main
  README.md
Labels: chore

#164 feat : 강제퇴장 기능 구현 및 테스트
  README.md
  src/app/(chat)/_components/molecules/AgoraUserList.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(main)/_components/molecules/AgoraListDecider.tsx
  src/app/(main)/user-info/_lib/deleteUserAccount.ts
  src/store/kick.ts
Labels: Type: Enhancement, Priority: High, feat

#166 아고라 채팅방에서 새로고침시 뜨는 경고창 취소시 홈으로 이동하는 버그 수정
  README.md
  src/hooks/useUnloadDisconnectSocket.tsx
Labels: Priority: Urgent, fix

#167 dev -> main
  README.md
  src/hooks/useUnloadDisconnectSocket.tsx
Labels: Type: Maintenance, refactor

#168 홈 화면 버그 수정
  src/app/(main)/_components/atoms/CategoryAgoraNowTitle.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/_components/templates/SignIn.tsx
  src/app/(main)/_lib/postEnterAgoraInfo.ts
Labels: Type: Bug, Priority: High, fix

#172 카테고리별 새로고침 작동 안되는 문제 수정
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(main)/_components/atoms/CategoryAgoraNowTitle.tsx
  src/app/(main)/_components/molecules/AgoraListDecider.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
Labels: Type: Bug, Priority: High, fix

#174 채팅방 새로고침 시 프로필 유지하도록 개선
  src/app/(chat)/_components/atoms/ChatPageLoading.tsx
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/layout.tsx
  src/app/(main)/_components/atoms/CategoryAgoraNowTitle.tsx
  src/app/(main)/_components/molecules/AgoraListDecider.tsx
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/(main)/layout.tsx
  src/app/_components/utils/SetChatInfoReset.tsx
  src/app/config/ChatPageLoadConfig.tsx
  src/constants/responseErrorMessage.ts
  src/hooks/useUnloadDisconnectSocket.tsx
  src/store/agora.ts
  src/store/enter.ts
Labels: Type: Bug, Priority: High, fix

#175 채팅방 새로고침 시 재입장 및 프로필 유지하도록 개선 dev -> main
  src/app/(chat)/_components/atoms/ChatPageLoading.tsx
  src/app/(chat)/_components/molecules/Message.tsx
  src/app/(chat)/_components/organisms/Header.tsx
  src/app/(chat)/layout.tsx
  src/app/(main)/_components/atoms/CategoryAgoraNowTitle.tsx
  src/app/(main)/_components/molecules/AgoraListDecider.tsx
  src/app/(main)/_components/molecules/CategoryAgoraList.tsx
  src/app/(main)/_lib/postEnterAgoraInfo.ts
  src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
  src/app/(main)/layout.tsx
  src/app/_components/utils/SetChatInfoReset.tsx
  src/app/config/ChatPageLoadConfig.tsx
  src/constants/responseErrorMessage.ts
  src/hooks/useUnloadDisconnectSocket.tsx
  src/store/agora.ts
  src/store/enter.ts
Labels: Type: Bug, Priority: High, fix

#176 다크모드에서 새로고침시 라이트모드로 깜빡이는 문제 수정
  src/app/(chat)/_components/atoms/ChatPageLoading.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(main)/_components/atoms/CategoryAgoraNowTitle.tsx
  src/app/(main)/_components/atoms/ThemeSwitcher.tsx
  src/app/(main)/_components/atoms/VirtuosoGridCustomList.tsx
  src/app/(main)/_components/molecules/LivelyAgoraList.tsx
  src/app/(main)/_components/molecules/PageTitle.tsx
  src/app/_components/utils/SetTheme.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/assets/icons/ArrowDownIcon.tsx
  src/assets/icons/Athens.tsx
  src/assets/icons/BackIcon.tsx
  src/assets/icons/CheckCircleIcon.tsx
  src/assets/icons/CheckIcon.tsx
  src/assets/icons/EyeIcon.tsx
  src/assets/icons/HamburgerIcon.tsx
  src/assets/icons/RefreshIcon.tsx
  src/assets/icons/RemoveIcon.tsx
  src/assets/icons/SearchIcon.tsx
  src/assets/icons/SendIcon.tsx
  src/assets/icons/ShareIcon.tsx
  src/assets/icons/UserIcon.tsx
  src/assets/icons/addIcon.tsx
  src/assets/icons/homeIcon.tsx
  src/constants/theme.ts
  src/serverActions/theme.ts
  src/store/darkMode.ts
  src/store/theme.ts
Labels: Type: Bug, Priority: High, fix

#177 다크모드에서 새로고침 시 라이트 모드 깜빡임 문제 수정 dev -> main
  src/app/(chat)/_components/atoms/ChatPageLoading.tsx
  src/app/(chat)/_components/molecules/MessageInput.tsx
  src/app/(main)/_components/atoms/CategoryAgoraNowTitle.tsx
  src/app/(main)/_components/atoms/ThemeSwitcher.tsx
  src/app/(main)/_components/atoms/VirtuosoGridCustomList.tsx
  src/app/(main)/_components/molecules/LivelyAgoraList.tsx
  src/app/(main)/_components/molecules/PageTitle.tsx
  src/app/_components/utils/SetTheme.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/assets/icons/ArrowDownIcon.tsx
  src/assets/icons/Athens.tsx
  src/assets/icons/BackIcon.tsx
  src/assets/icons/CheckCircleIcon.tsx
  src/assets/icons/CheckIcon.tsx
  src/assets/icons/EyeIcon.tsx
  src/assets/icons/HamburgerIcon.tsx
  src/assets/icons/RefreshIcon.tsx
  src/assets/icons/RemoveIcon.tsx
  src/assets/icons/SearchIcon.tsx
  src/assets/icons/SendIcon.tsx
  src/assets/icons/ShareIcon.tsx
  src/assets/icons/UserIcon.tsx
  src/assets/icons/addIcon.tsx
  src/assets/icons/homeIcon.tsx
  src/constants/theme.ts
  src/serverActions/theme.ts
  src/store/darkMode.ts
  src/store/theme.ts
Labels: Type: Bug, Priority: High, fix
